import { CommitteeMember } from '@/types';

export const mockCommitteeMembers: CommitteeMember[] = [
  // 1. Key Leadership (सभापती, उपसभापती, सचिव)
  {
    id: 'lead-1',
    name_mr: 'मा. श्री. बाळासाहेब गणपतराव पाटील',
    name_en: 'Hon. Shri. Balasaheb Ganpatrao Patil',
    role_type: 'leadership',
    designation_mr: 'सभापती',
    designation_en: 'Chairman',
    phone: '+91 98220 12345',
    email: 'chairman@apmcmalkapur.org',
    image_url: null, // Will use placeholder in UI
    term_start: '2023',
    term_end: 'Present',
    village_mr: 'मलकापूर',
    village_en: 'Malkapur',
    sort_order: 1,
    is_active: true
  },
  {
    id: 'lead-2',
    name_mr: 'मा. श्री. रामदास विठ्ठलराव तायडे',
    name_en: 'Hon. Shri. Ramdas Vitthalrao Tayade',
    role_type: 'leadership',
    designation_mr: 'उपसभापती',
    designation_en: 'Vice Chairman',
    phone: '+91 98500 54321',
    email: 'vicechairman@apmcmalkapur.org',
    image_url: null,
    term_start: '2023',
    term_end: 'Present',
    village_mr: 'नरवेल',
    village_en: 'Narwel',
    sort_order: 2,
    is_active: true
  },
  {
    id: 'lead-3',
    name_mr: 'श्री. सदाशिव नामदेवराव वानखडे',
    name_en: 'Shri. Sadashiv Namdevrao Wankhade',
    role_type: 'leadership',
    designation_mr: 'सचिव',
    designation_en: 'Secretary',
    phone: '+91 94221 67890',
    email: 'secretary@apmcmalkapur.org',
    image_url: null,
    term_start: '2020',
    term_end: 'Present',
    village_mr: 'उमळी',
    village_en: 'Umali',
    sort_order: 3,
    is_active: true
  },

  // 2. Board Members (संचालक मंडळ सदस्य)
  {
    id: 'board-1',
    name_mr: 'श्री. गजानन देवराव पाटील',
    name_en: 'Shri. Gajanan Devrao Patil',
    role_type: 'board',
    designation_mr: 'संचालक',
    designation_en: 'Director',
    village_mr: 'वडजी (सहकारी संस्था गट)',
    village_en: 'Wadji (Cooperative Societies Group)',
    sort_order: 10,
    is_active: true
  },
  {
    id: 'board-2',
    name_mr: 'श्री. निवृत्ती नामदेव चोपडे',
    name_en: 'Shri. Nivruti Namdeo Chopade',
    role_type: 'board',
    designation_mr: 'संचालक',
    designation_en: 'Director',
    village_mr: 'माळखेड (सहकारी संस्था गट)',
    village_en: 'Malkhed (Cooperative Societies Group)',
    sort_order: 11,
    is_active: true
  },
  {
    id: 'board-3',
    name_mr: 'सौ. शालिनीबाई गोपाळराव देशमुख',
    name_en: 'Sau. Shalinibai Gopalrao Deshmukh',
    role_type: 'board',
    designation_mr: 'संचालक',
    designation_en: 'Director',
    village_mr: 'मलकापूर (महिला राखीव गट)',
    village_en: 'Malkapur (Women\'s Reserved Group)',
    sort_order: 12,
    is_active: true
  },
  {
    id: 'board-4',
    name_mr: 'श्री. समाधान बाळकृष्ण तायडे',
    name_en: 'Shri. Samadhan Balkrishna Tayade',
    role_type: 'board',
    designation_mr: 'संचालक',
    designation_en: 'Director',
    village_mr: 'नरवेल (इतर मागासवर्गीय गट)',
    village_en: 'Narwel (OBC Group)',
    sort_order: 13,
    is_active: true
  },
  {
    id: 'board-5',
    name_mr: 'श्री. ज्ञानेश्वर तुकाराम महाले',
    name_en: 'Shri. Dnyaneshwar Tukaram Mahale',
    role_type: 'board',
    designation_mr: 'संचालक',
    designation_en: 'Director',
    village_mr: 'धसाडी (ग्रामपंचायत गट)',
    village_en: 'Dhasadi (Gram Panchayat Group)',
    sort_order: 14,
    is_active: true
  },
  {
    id: 'board-6',
    name_mr: 'श्री. भगवान विष्णू कोलते',
    name_en: 'Shri. Bhagwan Vishnu Kolte',
    role_type: 'board',
    designation_mr: 'संचालक',
    designation_en: 'Director',
    village_mr: 'भडगणी (कृषी पतसंस्था गट)',
    village_en: 'Bhadgani (Cooperative Credit Group)',
    sort_order: 15,
    is_active: true
  },
  {
    id: 'board-7',
    name_mr: 'श्री. वासुदेव शंकर सोनोने',
    name_en: 'Shri. Vasudev Shankar Sonone',
    role_type: 'board',
    designation_mr: 'संचालक',
    designation_en: 'Director',
    village_mr: 'उमळी (विमुक्त जाती / भटक्या जमाती गट)',
    village_en: 'Umali (VJ/NT Group)',
    sort_order: 16,
    is_active: true
  },
  {
    id: 'board-8',
    name_mr: 'श्री. शेख हुसेन शेख कादर',
    name_en: 'Shri. Sheikh Husain Sheikh Kadar',
    role_type: 'board',
    designation_mr: 'संचालक',
    designation_en: 'Director',
    village_mr: 'मलकापूर (व्यापारी / अडते गट)',
    village_en: 'Malkapur (Traders & Commission Agents Group)',
    sort_order: 17,
    is_active: true
  },
  {
    id: 'board-9',
    name_mr: 'श्री. प्रकाश अर्जुन जुमळे',
    name_en: 'Shri. Prakash Arjun Jumale',
    role_type: 'board',
    designation_mr: 'संचालक',
    designation_en: 'Director',
    village_mr: 'मलकापूर (हमाल व तोलणार गट)',
    village_en: 'Malkapur (Labourers & Weighmen Group)',
    sort_order: 18,
    is_active: true
  },

  // 3. Employees / Officers (अधिकारी व कर्मचारी)
  {
    id: 'emp-1',
    name_mr: 'श्री. विकास सखाराम सोनोने',
    name_en: 'Shri. Vikas Sakharam Sonone',
    role_type: 'officer',
    designation_mr: 'सहाय्यक सचिव',
    designation_en: 'Assistant Secretary',
    department_mr: 'प्रशासन विभाग',
    department_en: 'Administration Dept',
    phone: '+91 94228 11111',
    sort_order: 30,
    is_active: true
  },
  {
    id: 'emp-2',
    name_mr: 'श्री. अर्जुन विठ्ठलराव तायडे',
    name_en: 'Shri. Arjun Vitthalrao Tayade',
    role_type: 'officer',
    designation_mr: 'मुख्य लेखापाल',
    designation_en: 'Chief Accountant',
    department_mr: 'वित्त व लेखा विभाग',
    department_en: 'Finance & Accounts Dept',
    phone: '+91 98605 22222',
    sort_order: 31,
    is_active: true
  },
  {
    id: 'emp-3',
    name_mr: 'श्री. संजय गजानन चोपडे',
    name_en: 'Shri. Sanjay Gajanan Chopade',
    role_type: 'employee',
    designation_mr: 'बाजार निरीक्षक',
    designation_en: 'Market Inspector',
    department_mr: 'बाजार व व्यापार विभाग',
    department_en: 'Market & Trading Dept',
    phone: '+91 94234 33333',
    sort_order: 32,
    is_active: true
  },
  {
    id: 'emp-4',
    name_mr: 'सौ. ज्योती दिनकर पाटील',
    name_en: 'Sau. Jyoti Dinkar Patil',
    role_type: 'employee',
    designation_mr: 'वरिष्ठ लिपिक',
    designation_en: 'Senior Clerk',
    department_mr: 'प्रशासन विभाग',
    department_en: 'Administration Dept',
    phone: '+91 98812 44444',
    sort_order: 33,
    is_active: true
  },
  {
    id: 'emp-5',
    name_mr: 'श्री. किरण वासुदेव सुरळकर',
    name_en: 'Shri. Kiran Vasudev Suralkar',
    role_type: 'employee',
    designation_mr: 'कनिष्ठ लिपिक',
    designation_en: 'Junior Clerk',
    department_mr: 'बाजार व व्यापार विभाग',
    department_en: 'Market & Trading Dept',
    phone: '+91 99223 55555',
    sort_order: 34,
    is_active: true
  },
  {
    id: 'emp-6',
    name_mr: 'श्री. राजू दगडू सोळंकी',
    name_en: 'Shri. Raju Dagdu Solanki',
    role_type: 'employee',
    designation_mr: 'तोलणार',
    designation_en: 'Weighman',
    department_mr: 'बाजार व व्यापार विभाग',
    department_en: 'Market & Trading Dept',
    phone: '+91 95456 66666',
    sort_order: 35,
    is_active: true
  },
  {
    id: 'emp-7',
    name_mr: 'श्री. गजानन भिकाजी तायडे',
    name_en: 'Shri. Gajanan Bhikaji Tayade',
    role_type: 'employee',
    designation_mr: 'शिपाई',
    designation_en: 'Peon',
    department_mr: 'सामान्य प्रशासन विभाग',
    department_en: 'General Administration Dept',
    phone: '+91 91588 77777',
    sort_order: 36,
    is_active: true
  }
];
